### PR TITLE
Update for julia 0.7

### PR DESCRIPTION
**Pull request by kdw503**
This resolved all the deprecation warnings under julia 0.7.

### CODE REVIEW

**Comment by timholy** [comment]
See also #10. This package is suddenly all the rage!

**Comment by PaulBellette** [comment]
Hey thanks for that! You make me feel lazy, I've had no time to look at this package in eons. @andyferris or @JoshChristie have all the power over this repo these days...

**Comment by c42f** [comment]
@JoshChristie or @andyferris you could probably add @PaulBellette back as a collaborator just for this repo.

Looking through both this and #10 they are almost identical but I'd merge this in preference due to a few additional niceties (adding 1.0 support in CI, an updated appveyor config, fwiw, and on the whole slightly more idiomatic julia code rewrite).

**Comment by andyferris** [comment]
> @JoshChristie or @andyferris you could probably add @PaulBellette back as a collaborator just for this repo.

Done. I didn't realize you that "external collaborator" to the organization didn't give access to the repos.

**Comment by c42f** [comment]
Oh, I didn't realise we were classed as external collaborators still. There are per-collaborator permissions perhaps those were just set oddly.

**Comment by kdw503** [comment]
Thank you all for reviewing and merging this commit.
Is it possible to tag a new version number for this merging?

**Comment by andyferris** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/18752

**Pull request merged**
