### PR TITLE
Update for Julia 0.6

### PR DESCRIPTION
**Pull request by timholy**
Because `.!` doesn't even parse prior to 0.6, I bumped the required Julia version. Will need a minor version bump when released.

### CODE REVIEW

**Comment by timholy** [comment]
I guess it's also worth pointing out these could be changed to `map(!, A)` if you prefer.

**Comment by c42f** [comment]
Thanks Tim, and thanks for updating the appveyor config.  We didn't have that enabled, but I've added it now.

I like the idea of using `map` for now.

**Comment by timholy** [comment]
OK, updated. I should point out that on 0.4 it gives these warnings:
```julia
julia> include("src/Munkres.jl")
Munkres

julia> include("test/runtests.jl")
WARNING: Method definition nthperm(AbstractArray{#T<:Integer, 1}) in module Base at combinatorics.jl:92 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/permutations.jl:161.
WARNING: Method definition nthperm(AbstractArray{T<:Any, 1}, Integer) in module Base at combinatorics.jl:89 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/permutations.jl:157.
WARNING: Method definition nthperm!(AbstractArray{T<:Any, 1}, Integer) in module Base at combinatorics.jl:70 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/permutations.jl:136.
WARNING: Method definition permutations(Any) in module Base at combinatorics.jl:219 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/permutations.jl:24.
WARNING: Method definition parity(AbstractArray{#T<:Integer, 1}) in module Base at combinatorics.jl:642 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/permutations.jl:221.
WARNING: Method definition levicivita(AbstractArray{#T<:Integer, 1}) in module Base at combinatorics.jl:611 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/permutations.jl:188.
WARNING: Method definition combinations(Any, Integer) in module Base at combinatorics.jl:182 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/combinations.jl:42.
WARNING: Method definition factorial(#T<:Integer, #T<:Integer) in module Base at combinatorics.jl:56 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/factorials.jl:18.
WARNING: Method definition factorial(Integer, Integer) in module Base at combinatorics.jl:66 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/factorials.jl:28.
WARNING: Method definition partitions(Integer) in module Base at combinatorics.jl:252 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/partitions.jl:26.
WARNING: Method definition partitions(Integer, Integer) in module Base at combinatorics.jl:318 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/partitions.jl:93.
WARNING: Method definition partitions(AbstractArray{T<:Any, 1}) in module Base at combinatorics.jl:380 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/partitions.jl:158.
WARNING: Method definition partitions(AbstractArray{T<:Any, 1}, Int64) in module Base at combinatorics.jl:447 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/partitions.jl:228.
WARNING: Method definition prevprod(Array{Int64, 1}, Any) in module Base at combinatorics.jl:565 overwritten in module Combinatorics at /home/tim/.julia/v0.4/Combinatorics/src/partitions.jl:354.

julia> 
```

**Comment by timholy** [comment]
~~Hmm, seems like 0.4 is not testable on OSX right now. Bump to 0.5?~~ Oh, NVM, it just seems flaky. Worked a second time.

**Comment by c42f** [comment]
No worries, the 0.4 support seems pretty superfluous at this stage :-)

Thanks a heap for fixing up the appveyor build.  I didn't mean to create extra work for you by enabling it!

**Pull request merged**
