### PR TITLE
update to 0.7+ and fix tests

### PR DESCRIPTION
**Pull request by alexmorley**

### CODE REVIEW

**Comment by timholy** [comment]
See also #11

**Comment by PaulBellette** [comment]
Awesome work! Unfortunately no merging powers... @andyferris and @JoshChristie

**Review by andyferris — APPROVED** [review]

**Comment by c42f** [comment]
Ah there's almost complete similarity with #11! I'd suggest merging #11 due to some additional niceties as mentioned over there.

**Comment by JoshChristie** [comment]
Thanks @alexmorley. I merged #11 which had many of these features and a few more additions.

**Pull request closed without merging**
